import { Button } from "@/components/ui/button";
import { Input }  from "@/components/ui/input";
import { Badge }  from "@/components/ui/badge";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import {
  BarChart3,
  X,
  ShieldCheck,
  ShieldOff,
  Clock,
  Lock,
} from "lucide-react";
import { formatNumber } from "@/lib/formatters";
import { getInvoiceRowClass, isOversellRow } from "@/lib/invoice-row-classes";
import {
  BUSINESS_CLASSIFICATION_LABELS,
  BUSINESS_CLASSIFICATION_COLORS,
} from "@shared/resolve-business-classification";
import { getUnitName } from "../utils/units";
import { getUnitOptions } from "@/lib/invoice-lines";
import type { LineLocal } from "../types";

function isExpiryNear(month: number | null | undefined, year: number | null | undefined): boolean {
  if (!month || !year) return false;
  const now    = new Date();
  const expiry = new Date(year, month - 1, 1);
  const diffMs = expiry.getTime() - now.getTime();
  return diffMs / (1000 * 60 * 60 * 24 * 30.44) < 3;
}

type KnownLineType = "service" | "drug" | "consumable" | "equipment" | "doctor_cost";

const LINE_TYPE_CONFIG: Record<KnownLineType, { label: string; className: string }> = {
  service:     { label: "خدمة",      className: "bg-blue-100 text-blue-700 dark:bg-blue-950/50 dark:text-blue-400 border-blue-300" },
  drug:        { label: "دواء",      className: "bg-green-100 text-green-700 dark:bg-green-950/50 dark:text-green-400 border-green-300" },
  consumable:  { label: "مستهلك",   className: "bg-orange-100 text-orange-700 dark:bg-orange-950/50 dark:text-orange-400 border-orange-300" },
  equipment:   { label: "جهاز",     className: "bg-purple-100 text-purple-700 dark:bg-purple-950/50 dark:text-purple-400 border-purple-300" },
  doctor_cost: { label: "أجر طبيب", className: "bg-rose-100 text-rose-700 dark:bg-rose-950/50 dark:text-rose-400 border-rose-300" },
};

function getLineTypeBadge(lineType: string) {
  const cfg = LINE_TYPE_CONFIG[lineType as KnownLineType];
  if (!cfg) return <Badge variant="outline" className="text-[10px] px-1">{lineType}</Badge>;
  return (
    <Badge variant="outline" className={`text-[10px] px-1.5 py-0 font-medium leading-none ${cfg.className}`}>
      {cfg.label}
    </Badge>
  );
}

function getBizClassBadge(bc: string | null | undefined) {
  if (!bc) return null;
  const label = BUSINESS_CLASSIFICATION_LABELS[bc as keyof typeof BUSINESS_CLASSIFICATION_LABELS] ?? bc;
  const color = BUSINESS_CLASSIFICATION_COLORS[bc as keyof typeof BUSINESS_CLASSIFICATION_COLORS] ?? "bg-gray-100 text-gray-700 border-gray-300";
  return (
    <Badge variant="outline" className={`text-[9px] px-1 py-0 leading-none ${color}`}>
      {label}
    </Badge>
  );
}

function isAutoGenerated(line: LineLocal): boolean {
  return line.sourceType === "STAY_ENGINE";
}

function isDoctorCostLine(line: LineLocal): boolean {
  return line.lineType === "doctor_cost";
}

function getPriceSourceBadge(line: LineLocal) {
  const isService = line.lineType === "service";
  if (line.priceSource === "department") {
    return <Badge variant="secondary" className="text-[9px] px-1 py-0 leading-none bg-green-100 text-green-700">قسم</Badge>;
  }
  if (!isService) return null;
  if (line.priceSource === "manual_override") {
    return <Badge variant="outline" className="text-[9px] px-1 py-0 leading-none bg-orange-50 text-orange-700 border-orange-300">✏ يدوي</Badge>;
  }
  if (line.priceSource === "contract_price_list") {
    return <Badge variant="outline" className="text-[9px] px-1 py-0 leading-none bg-blue-50 text-blue-700 border-blue-200">عقد</Badge>;
  }
  if (line.priceSource === "default_price_list") {
    return <Badge variant="outline" className="text-[9px] px-1 py-0 leading-none bg-amber-50 text-amber-700 border-amber-200">افتراضي</Badge>;
  }
  return null;
}

export interface InvoiceLineRowProps {
  line: LineLocal;
  index: number;
  isDraft: boolean;
  updateLine: (tempId: string, field: string, value: unknown) => void;
  removeLine: (tempId: string) => void;
  handleQtyConfirm: (tempId: string) => void;
  handleUnitLevelChange: (tempId: string, level: "major" | "medium" | "minor") => void;
  openStatsPopup: (itemId: string, name: string) => void;
  getServiceRowClass: (serviceType: string) => string;
  pendingQtyRef?: React.MutableRefObject<Map<string, string>>;
}

export function InvoiceLineRow({
  line,
  index: i,
  isDraft,
  updateLine,
  removeLine,
  handleQtyConfirm,
  handleUnitLevelChange,
  openStatsPopup,
  getServiceRowClass,
  pendingQtyRef,
}: InvoiceLineRowProps) {
  const isCostLine  = isDoctorCostLine(line);
  const isService   = line.lineType === "service";
  const hasExpiry   = line.lineType === "drug" || line.lineType === "consumable";
  const hasStatsBtn = (line.lineType === "drug" || line.lineType === "consumable") && !!line.itemId;
  const isAutoLine  = isAutoGenerated(line);
  const isReadOnly  = isAutoLine || isCostLine;

  const rowClass = getInvoiceRowClass({
    isAutoLine: isAutoLine || isCostLine,
    isOversellNoStock: isOversellRow(
      line.lineType,
      line.item?.allowOversell,
      line.item?.availableQtyMinor,
    ),
  });

  const priceSourceBadge = getPriceSourceBadge(line);
  const bizBadge = getBizClassBadge(line.businessClassification);

  return (
    <tr
      className={`peachtree-grid-row ${isService ? getServiceRowClass(line.serviceType) : ""} ${rowClass} ${isCostLine ? "opacity-70 bg-rose-50/40 dark:bg-rose-950/20" : ""}`}
      data-testid={`row-line-unified-${i}`}
    >
      <td className="text-center text-muted-foreground text-xs py-1">{i + 1}</td>

      <td className="text-center py-1">
        <div className="flex items-center justify-center gap-0.5 flex-wrap">
          {getLineTypeBadge(line.lineType)}
          {bizBadge}
          {isReadOnly && (
            <Badge variant="outline" className={`text-[9px] px-1 py-0 leading-none ${isCostLine ? "text-rose-600 dark:text-rose-400 border-rose-300" : "text-sky-600 dark:text-sky-400 border-sky-300"}`}>
              {isCostLine ? "تكلفة" : "تلقائي"}
            </Badge>
          )}
        </div>
      </td>

      <td className="py-1">
        {isDraft && !isReadOnly ? (
          <div className="flex flex-row-reverse items-center gap-1">
            <Input
              value={line.description}
              onChange={(e) => updateLine(line.tempId, "description", e.target.value)}
              className="h-6 text-xs flex-1"
              data-testid={`input-desc-unified-${i}`}
            />
            {priceSourceBadge}
            {hasStatsBtn && (
              <Button
                variant="ghost" size="icon" className="h-6 w-6 shrink-0"
                onClick={() => openStatsPopup(line.itemId!, line.description)}
                data-testid={`button-stock-stats-unified-${i}`}
              >
                <BarChart3 className="h-3 w-3 text-muted-foreground" />
              </Button>
            )}
          </div>
        ) : (
          <div className="flex flex-row-reverse items-center gap-1 flex-wrap">
            <span className="text-xs">{line.description}</span>
            {hasStatsBtn && (
              <Button
                variant="ghost" size="icon" className="h-5 w-5 shrink-0"
                onClick={() => openStatsPopup(line.itemId!, line.description)}
                data-testid={`button-stock-stats-ro-${i}`}
              >
                <BarChart3 className="h-3 w-3 text-muted-foreground" />
              </Button>
            )}
            {priceSourceBadge}
            {line.coverageStatus && line.coverageStatus !== "not_required" && (
              <TooltipProvider>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <span>
                      {line.coverageStatus === "covered" ? (
                        <Badge className="text-[9px] px-1 py-0 leading-none bg-green-100 dark:bg-green-950/40 text-green-700 dark:text-green-400 border-green-300 gap-0.5 cursor-help">
                          <ShieldCheck className="h-2.5 w-2.5" />مشمول
                        </Badge>
                      ) : line.coverageStatus === "excluded" ? (
                        <Badge className="text-[9px] px-1 py-0 leading-none bg-red-100 dark:bg-red-950/40 text-red-700 dark:text-red-400 border-red-300 gap-0.5 cursor-help">
                          <ShieldOff className="h-2.5 w-2.5" />مستثنى
                        </Badge>
                      ) : (
                        <Badge variant="secondary" className="text-[9px] px-1 py-0 leading-none gap-0.5 cursor-help">
                          <ShieldCheck className="h-2.5 w-2.5" />{line.coverageStatus}
                        </Badge>
                      )}
                    </span>
                  </TooltipTrigger>
                  <TooltipContent side="top" dir="rtl" className="max-w-xs text-xs leading-relaxed">
                    {line.coverageStatus === "covered" && line.companyShareAmount && (
                      <div>
                        <span className="font-medium">نصيب الشركة: </span>
                        {formatNumber(parseFloat(line.companyShareAmount || "0"))} ج.م
                      </div>
                    )}
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            )}
            {line.approvalStatus === "pending" && (
              <Badge className="text-[9px] px-1 py-0 leading-none bg-amber-100 dark:bg-amber-950/40 text-amber-700 dark:text-amber-400 border-amber-300 gap-0.5">
                <Clock className="h-2.5 w-2.5" />موافقة
              </Badge>
            )}
            {line.coverageStatus === "covered" && line.companyShareAmount && parseFloat(line.companyShareAmount) > 0 && (
              <Badge variant="outline" className="text-[9px] px-1 py-0 leading-none text-blue-700 dark:text-blue-400 border-blue-300">
                شركة: {formatNumber(parseFloat(line.companyShareAmount))}
              </Badge>
            )}
            {line.coverageStatus === "covered" && line.patientShareAmount && parseFloat(line.patientShareAmount) > 0 && (
              <Badge variant="outline" className="text-[9px] px-1 py-0 leading-none text-orange-700 dark:text-orange-400 border-orange-300">
                مريض: {formatNumber(parseFloat(line.patientShareAmount))}
              </Badge>
            )}
          </div>
        )}
      </td>

      <td className={`text-center py-1 ${isService && line.requiresDoctor ? "bg-blue-50 dark:bg-blue-950/40" : ""}`}>
        {isService && line.requiresDoctor ? (
          isDraft ? (
            <Input
              value={line.doctorName}
              onChange={(e) => updateLine(line.tempId, "doctorName", e.target.value)}
              placeholder="الطبيب *"
              className={`h-6 text-xs ${!line.doctorName ? "border-blue-400 dark:border-blue-600" : ""}`}
              data-testid={`input-doctor-unified-${i}`}
            />
          ) : (
            <span className="text-xs">{line.doctorName || "-"}</span>
          )
        ) : (
          <span className="text-xs text-muted-foreground">—</span>
        )}
      </td>

      <td className={`text-center py-1 ${isService && line.requiresNurse ? "bg-purple-50 dark:bg-purple-950/40" : ""}`}>
        {isService && line.requiresNurse ? (
          isDraft ? (
            <Input
              value={line.nurseName}
              onChange={(e) => updateLine(line.tempId, "nurseName", e.target.value)}
              placeholder="الممرض *"
              className={`h-6 text-xs ${!line.nurseName ? "border-purple-400 dark:border-purple-600" : ""}`}
              data-testid={`input-nurse-unified-${i}`}
            />
          ) : (
            <span className="text-xs">{line.nurseName || "-"}</span>
          )
        ) : (
          <span className="text-xs text-muted-foreground">—</span>
        )}
      </td>

      <td className={`text-center py-1 ${
        !isService && line.unitLevel === "medium"
          ? "bg-orange-100 dark:bg-orange-900/30"
          : !isService && line.unitLevel === "minor"
          ? "bg-rose-100 dark:bg-rose-900/30"
          : ""
      }`}>
        {!isService && line.itemId && line.item ? (
          isDraft ? (
            <select
              value={line.unitLevel}
              onChange={(e) => handleUnitLevelChange(line.tempId, e.target.value as "major" | "medium" | "minor")}
              className={`h-6 text-xs rounded border w-full text-center bg-background ${
                line.unitLevel === "medium"
                  ? "border-orange-500 text-orange-800 dark:text-orange-200 bg-orange-50 dark:bg-orange-900/40"
                  : line.unitLevel === "minor"
                  ? "border-rose-500 text-rose-800 dark:text-rose-200 bg-rose-50 dark:bg-rose-900/40"
                  : ""
              }`}
              data-testid={`select-unit-unified-${i}`}
            >
              {getUnitOptions(line.item).map((opt) => (
                <option
                  key={opt.value}
                  value={opt.value}
                  disabled={!opt.priceable}
                  title={!opt.priceable ? "معامل التحويل غير معرّف لهذه الوحدة — يجب إعداد الصنف أولاً" : undefined}
                >
                  {opt.priceable ? opt.label : `${opt.label} (غير معرّف)`}
                </option>
              ))}
            </select>
          ) : (
            <span className={`text-xs font-bold ${
              line.unitLevel === "medium"
                ? "text-orange-700 dark:text-orange-300"
                : line.unitLevel === "minor"
                ? "text-rose-700 dark:text-rose-300"
                : "text-foreground font-normal"
            }`} data-testid={`text-unit-unified-${i}`}>
              {getUnitName(line.item, line.unitLevel)}
            </span>
          )
        ) : (
          <span className="text-xs text-muted-foreground">—</span>
        )}
      </td>

      <td className="text-center py-1">
        {isDraft && !isCostLine ? (
          isAutoGenerated(line) ? (
            <Input
              key={`stay-qty-${line.tempId}`}
              type="number"
              defaultValue={line.quantity === 0 ? "" : line.quantity}
              min="0"
              step="any"
              onBlur={(e) => {
                const days = parseFloat(e.target.value) || 0;
                updateLine(line.tempId, "quantity",   days);
                updateLine(line.tempId, "totalPrice", +(days * line.unitPrice).toFixed(2));
              }}
              onKeyDown={(e) => {
                if (e.key === "Enter") {
                  e.preventDefault();
                  const days = parseFloat((e.target as HTMLInputElement).value) || 0;
                  updateLine(line.tempId, "quantity",   days);
                  updateLine(line.tempId, "totalPrice", +(days * line.unitPrice).toFixed(2));
                  (e.target as HTMLInputElement).blur();
                }
              }}
              placeholder="الأيام"
              className={`h-6 text-xs text-center ${line.quantity === 0 ? "border-amber-400 bg-amber-50 dark:bg-amber-950/20" : ""}`}
              data-testid={`input-stay-days-${i}`}
            />
          ) : hasExpiry && line.lotId ? (
            <Input
              type="number"
              defaultValue={line.quantity}
              min={0} step="any"
              onChange={(e) => pendingQtyRef?.current.set(line.tempId, e.target.value)}
              onBlur={() => handleQtyConfirm(line.tempId)}
              onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); handleQtyConfirm(line.tempId); } }}
              className="h-6 text-xs text-center"
              data-testid={`input-qty-unified-${i}`}
            />
          ) : (
            <Input
              type="number"
              value={line.quantity}
              min={0} step="any"
              onChange={(e) => updateLine(line.tempId, "quantity", parseFloat(e.target.value) || 0)}
              className="h-6 text-xs text-center"
              data-testid={`input-qty-unified-${i}`}
            />
          )
        ) : (
          <span className="text-xs">
            {isAutoGenerated(line) && line.quantity === 0
              ? <span className="text-amber-600 text-[10px]">— أيام —</span>
              : formatNumber(line.quantity)}
          </span>
        )}
      </td>

      <td className={`text-center py-1 ${
        hasExpiry && isExpiryNear(line.expiryMonth, line.expiryYear)
          ? "bg-yellow-50 dark:bg-yellow-900/20"
          : ""
      }`} data-testid={`td-expiry-unified-${i}`}>
        {hasExpiry ? (
          line.expiryMonth && line.expiryYear ? (
            <span
              className={`text-[11px] font-mono font-semibold ${
                isExpiryNear(line.expiryMonth, line.expiryYear)
                  ? "text-amber-700 dark:text-amber-400"
                  : "text-foreground"
              }`}
              title={`دفعة ${line.lotId ? "(" + line.lotId.slice(0, 8) + "…)" : ""}`}
            >
              {String(line.expiryMonth).padStart(2, "0")}/{line.expiryYear}
            </span>
          ) : (
            <span className="text-[10px] text-muted-foreground">
              {isDraft ? "— جارٍ —" : "—"}
            </span>
          )
        ) : (
          <span className="text-muted-foreground">—</span>
        )}
      </td>

      <td className="text-center py-1">
        {isDraft && isCostLine ? (
          <Input
            type="number"
            value={line.unitPrice}
            min={0}
            step="0.01"
            onChange={(e) => {
              const val = parseFloat(e.target.value) || 0;
              updateLine(line.tempId, "unitPrice", val);
              updateLine(line.tempId, "totalPrice", val);
              updateLine(line.tempId, "doctorCostManualOverride", true);
            }}
            className="h-6 text-xs text-center"
            data-testid={`input-doctor-cost-price-${i}`}
          />
        ) : (
          <span
            className="flex items-center justify-center gap-0.5 peachtree-amount text-xs"
            title="سعر النظام"
            data-testid={`text-unit-price-unified-${i}`}
          >
            {isDraft && <Lock className="h-2.5 w-2.5 text-muted-foreground shrink-0" />}
            {formatNumber(line.unitPrice)}
          </span>
        )}
      </td>

      <td className="text-center py-1">
        {isDraft && !isCostLine ? (
          <Input
            type="number"
            value={line.discountPercent}
            min={0} max={100}
            onChange={(e) => updateLine(line.tempId, "discountPercent", parseFloat(e.target.value) || 0)}
            className="h-6 text-xs text-center"
            data-testid={`input-disc-pct-unified-${i}`}
          />
        ) : (
          <span className="text-xs">{formatNumber(line.discountPercent)}</span>
        )}
      </td>

      <td className="text-center py-1">
        {isDraft && !isCostLine ? (
          <Input
            type="number"
            value={line.discountAmount}
            min={0}
            onChange={(e) => updateLine(line.tempId, "discountAmount", parseFloat(e.target.value) || 0)}
            className="h-6 text-xs text-center"
            data-testid={`input-disc-amt-unified-${i}`}
          />
        ) : (
          <span className="text-xs">{formatNumber(line.discountAmount)}</span>
        )}
      </td>

      <td className="text-center font-bold text-xs py-1">{formatNumber(line.totalPrice)}</td>

      {isDraft && (
        <td className="text-center py-1">
          {!isCostLine && (
            <Button
              variant="ghost" size="icon" className="h-5 w-5"
              onClick={() => removeLine(line.tempId)}
              data-testid={`button-remove-line-unified-${i}`}
            >
              <X className="h-3 w-3 text-destructive" />
            </Button>
          )}
        </td>
      )}
    </tr>
  );
}
