import { useState, useEffect, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { getInvoiceRowClass, isOversellRow } from "@/lib/invoice-row-classes";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { Loader2, X, BarChart3, ShieldCheck, ShieldOff, Clock, FileText, Search as SearchIcon, Lock } from "lucide-react";
import { ItemFastSearch } from "@/components/ItemFastSearch/ItemFastSearch";
import type { ItemSelectedPayload } from "@/components/ItemFastSearch/types";
import type { ItemSearchResult } from "../hooks/useLineManagement";
import { useQuery } from "@tanstack/react-query";
import type { InvoiceTemplate } from "@shared/schema";
import { formatNumber } from "@/lib/formatters";
import type { Service, Item } from "@shared/schema";
import type { LineLocal } from "../types";
import {
  BUSINESS_CLASSIFICATION_LABELS,
  BUSINESS_CLASSIFICATION_COLORS,
} from "@shared/resolve-business-classification";
import {
  itemHasMajorUnit,
  itemHasMediumUnit,
  getUnitName,
} from "../utils/units";
import { getUnitOptions } from "@/lib/invoice-lines";
import { ServiceLookup } from "@/components/lookups";

// ── نوع البند — مخطط الألوان والتسميات ────────────────────────────────────────
type KnownLineType = "service" | "drug" | "consumable" | "equipment";

const LINE_TYPE_CONFIG: Record<KnownLineType, { label: string; className: string }> = {
  service:    { label: "خدمة",    className: "bg-blue-100 text-blue-700 dark:bg-blue-950/50 dark:text-blue-400 border-blue-300" },
  drug:       { label: "دواء",    className: "bg-green-100 text-green-700 dark:bg-green-950/50 dark:text-green-400 border-green-300" },
  consumable: { label: "مستهلك", className: "bg-orange-100 text-orange-700 dark:bg-orange-950/50 dark:text-orange-400 border-orange-300" },
  equipment:  { label: "جهاز",   className: "bg-purple-100 text-purple-700 dark:bg-purple-950/50 dark:text-purple-400 border-purple-300" },
};

function getLineTypeBadge(lineType: string) {
  const cfg = LINE_TYPE_CONFIG[lineType as KnownLineType];
  if (!cfg) return <Badge variant="outline" className="text-[10px] px-1">{lineType}</Badge>;
  return (
    <Badge variant="outline" className={`text-[10px] px-1.5 py-0 font-medium ${cfg.className}`}>
      {cfg.label}
    </Badge>
  );
}

// ── Stay Engine badge ──────────────────────────────────────────────────────────
function isAutoGenerated(line: LineLocal): boolean {
  return line.sourceType === "stay_engine" || line.priceSource === "stay_engine"
    || line.sourceType === "STAY_ENGINE";
}

// ── Business Classification badge ─────────────────────────────────────────────
function getBizClassBadge(bc: string | null | undefined) {
  if (!bc) {
    return (
      <Badge variant="outline" className="text-[9px] px-1 py-0 text-muted-foreground border-muted-foreground/40">
        غير مصنف
      </Badge>
    );
  }
  const label = BUSINESS_CLASSIFICATION_LABELS[bc as keyof typeof BUSINESS_CLASSIFICATION_LABELS] ?? bc;
  const color = BUSINESS_CLASSIFICATION_COLORS[bc as keyof typeof BUSINESS_CLASSIFICATION_COLORS] ?? "";
  return (
    <Badge variant="outline" className={`text-[9px] px-1 py-0 ${color}`}>
      {label}
    </Badge>
  );
}

// ── نوع الصنف المختار للإضافة ──────────────────────────────────────────────────
type ItemAddType = "drug" | "consumable" | "equipment";
const ITEM_ADD_TYPES: { value: ItemAddType; label: string; color: string }[] = [
  { value: "drug",       label: "دواء",    color: "bg-green-100 text-green-700 border-green-300 dark:bg-green-950/50 dark:text-green-400" },
  { value: "consumable", label: "مستهلك",  color: "bg-orange-100 text-orange-700 border-orange-300 dark:bg-orange-950/50 dark:text-orange-400" },
  { value: "equipment",  label: "جهاز",   color: "bg-purple-100 text-purple-700 border-purple-300 dark:bg-purple-950/50 dark:text-purple-400" },
];

// نحوّل category الصنف → lineType (مع دعم gas وservice)
function categoryToLineType(category: string | null | undefined, fallback: ItemAddType): ItemAddType {
  switch (category) {
    case "drug":        return "drug";
    case "equipment":   return "equipment";
    case "gas":         return "consumable";  // الغاز → مستهلك
    case "consumable":  return "consumable";
    default:            return fallback;
  }
}

interface UnifiedLinesTabProps {
  lines: LineLocal[];
  isDraft: boolean;

  // Item search state — kept for back-compat but no longer used in UI (ItemFastSearch handles search)
  itemSearch?: string;
  setItemSearch?: (v: string) => void;
  setItemResults?: (v: Item[]) => void;
  itemResults?: Item[];
  searchingItems?: boolean;
  fefoLoading: boolean;
  itemSearchRef?: React.RefObject<HTMLInputElement>;
  itemDropdownRef?: React.RefObject<HTMLDivElement>;
  pendingQtyRef?: React.MutableRefObject<Map<string, string>>;

  // Mutation functions
  addServiceLine: (svc: Service) => void;
  addItemLine: (item: Item, type: ItemAddType) => void;
  updateLine: (tempId: string, field: string, value: unknown) => void;
  removeLine: (tempId: string) => void;
  handleQtyConfirm: (tempId: string) => void;
  handleUnitLevelChange: (tempId: string, level: "major" | "medium" | "minor") => void;
  openStatsPopup: (itemId: string, name: string) => void;
  getServiceRowClass: (serviceType: string) => string;
  applyTemplate?: (templateId: string, opts?: { replaceExisting?: boolean }) => Promise<void>;
  // For ItemFastSearch
  warehouseId?: string;
  invoiceDate?: string;
}

export function UnifiedLinesTab({
  lines,
  isDraft,
  itemSearch, setItemSearch, setItemResults, itemResults, searchingItems, fefoLoading,
  itemSearchRef, itemDropdownRef, pendingQtyRef,
  addServiceLine, addItemLine, updateLine, removeLine,
  handleQtyConfirm, handleUnitLevelChange, openStatsPopup, getServiceRowClass,
  applyTemplate,
  warehouseId = "",
  invoiceDate,
}: UnifiedLinesTabProps) {
  const [sourceMode, setSourceMode] = useState<"service" | "item">("service");
  const [itemAddType, setItemAddType] = useState<ItemAddType>("drug");
  const [fastSearchOpen, setFastSearchOpen] = useState(false);

  // F2 shortcut to open ItemFastSearch
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === "F2" && isDraft && !fastSearchOpen) {
        e.preventDefault();
        setSourceMode("item");
        setFastSearchOpen(true);
      }
    }
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [isDraft, fastSearchOpen]);

  // Adapter: FastSearchItem → ItemSearchResult → addItemLine
  const handleFastItemSelected = useCallback((payload: ItemSelectedPayload) => {
    const { item } = payload;
    const adapted: ItemSearchResult = {
      id: item.id,
      nameAr: item.nameAr,
      itemCode: item.itemCode,
      hasExpiry: item.hasExpiry,
      allowOversell: item.allowOversell ?? null,
      availableQtyMinor: item.availableQtyMinor,
      salePriceCurrent: item.salePriceCurrent,
      purchasePriceLast: undefined,
      businessClassification: undefined,
      majorUnitName: item.majorUnitName,
      mediumUnitName: item.mediumUnitName,
      minorUnitName: item.minorUnitName,
      majorToMedium: item.majorToMedium ? Number(item.majorToMedium) : null,
      majorToMinor:  item.majorToMinor  ? Number(item.majorToMinor)  : null,
      mediumToMinor: item.mediumToMinor ? Number(item.mediumToMinor) : null,
    };
    // تحديد النوع تلقائياً من category الصنف (دواء / مستهلك / جهاز / غاز)
    const lineType = categoryToLineType(item.category, itemAddType);
    addItemLine(adapted as unknown as Item, lineType);
    setFastSearchOpen(false);
  }, [addItemLine, itemAddType]);
  const [selectedServiceId, setSelectedServiceId] = useState("");
  const [selectedTemplateId, setSelectedTemplateId] = useState("__none__");
  const [applyingTemplate, setApplyingTemplate] = useState(false);
  const [replaceExisting, setReplaceExisting] = useState(false);

  const { data: templates } = useQuery<InvoiceTemplate[]>({
    queryKey: ["/api/invoice-templates"],
    enabled: isDraft && !!applyTemplate,
  });

  async function handleApplyTemplate() {
    if (!applyTemplate || !selectedTemplateId || selectedTemplateId === "__none__") return;
    setApplyingTemplate(true);
    try {
      await applyTemplate(selectedTemplateId, { replaceExisting });
      setSelectedTemplateId("__none__");
    } finally {
      setApplyingTemplate(false);
    }
  }

  const colSpanFull = isDraft ? 12 : 11;

  return (
    <div className="space-y-2">

      {/* ══ شريط إضافة البنود (سطر واحد مضغوط) ════════════════════════════════ */}
      {isDraft && (
        <div className="flex items-center gap-1.5 border rounded-md px-2 py-1 bg-muted/20 flex-wrap" dir="rtl">

          {/* ── نموذج (إذا وُجد) ─────────────────── */}
          {applyTemplate && templates && templates.length > 0 && (
            <>
              <FileText className="h-3 w-3 text-muted-foreground shrink-0" />
              <Select value={selectedTemplateId} onValueChange={setSelectedTemplateId} disabled={applyingTemplate}>
                <SelectTrigger className="h-6 text-[11px] w-36 px-1" data-testid="select-template">
                  <SelectValue placeholder="نموذج..." />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__none__">— نموذج —</SelectItem>
                  {templates.map(t => (
                    <SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <Button
                size="sm"
                variant="secondary"
                className="h-6 text-[11px] px-2 shrink-0"
                onClick={handleApplyTemplate}
                disabled={selectedTemplateId === "__none__" || applyingTemplate}
                data-testid="btn-apply-template"
              >
                {applyingTemplate ? <Loader2 className="h-3 w-3 animate-spin" /> : "تطبيق"}
              </Button>
              <label className="flex items-center gap-1 cursor-pointer shrink-0" data-testid="toggle-replace-existing">
                <input
                  type="checkbox"
                  checked={replaceExisting}
                  onChange={e => setReplaceExisting(e.target.checked)}
                  disabled={applyingTemplate}
                  className="h-3 w-3 accent-primary"
                />
                <span className="text-[10px] text-muted-foreground">استبدال</span>
              </label>
              <div className="w-px h-4 bg-border/50 shrink-0" />
            </>
          )}

          {/* ── مفتاح المصدر: خدمة / صنف ───────── */}
          <span className="text-[10px] text-muted-foreground shrink-0">إضافة:</span>
          <div className="flex gap-0.5 shrink-0">
            <button
              type="button"
              onClick={() => setSourceMode("service")}
              data-testid="btn-source-service"
              className={`h-6 px-2.5 text-[11px] rounded border font-medium transition-colors ${
                sourceMode === "service"
                  ? "bg-primary text-primary-foreground border-primary"
                  : "border-border text-muted-foreground hover:bg-muted"
              }`}
            >
              خدمة
            </button>
            <button
              type="button"
              onClick={() => setSourceMode("item")}
              data-testid="btn-source-item"
              className={`h-6 px-2.5 text-[11px] rounded border font-medium transition-colors ${
                sourceMode === "item"
                  ? "bg-primary text-primary-foreground border-primary"
                  : "border-border text-muted-foreground hover:bg-muted"
              }`}
            >
              صنف
            </button>
          </div>

          {/* ── بحث عن خدمة ─────────────────────── */}
          {sourceMode === "service" && (
            <div className="flex-1 min-w-[180px]">
              <ServiceLookup
                value={selectedServiceId}
                onChange={(item) => {
                  if (item) {
                    addServiceLine(item.meta as Service);
                    setSelectedServiceId("");
                  }
                }}
                placeholder="بحث عن خدمة..."
                disabled={!isDraft || applyingTemplate}
                data-testid="input-service-search-unified"
              />
            </div>
          )}

          {/* ── بحث عن صنف (F2 modal) ─────────── */}
          {sourceMode === "item" && (
            <>
              <Button
                size="sm"
                variant="default"
                className="h-6 text-[11px] px-3 gap-1 shrink-0"
                onClick={() => setFastSearchOpen(true)}
                disabled={!isDraft || applyingTemplate || !warehouseId}
                data-testid="btn-open-item-fast-search"
              >
                <SearchIcon className="h-3 w-3" />
                بحث صنف
                <kbd className="text-[8px] bg-white/20 px-0.5 rounded border border-white/30">F2</kbd>
              </Button>
              {/* نوع احتياطي */}
              <span className="text-[9px] text-muted-foreground shrink-0">نوع احتياطي:</span>
              {ITEM_ADD_TYPES.map(t => (
                <button
                  key={t.value}
                  type="button"
                  onClick={() => setItemAddType(t.value)}
                  disabled={!isDraft || applyingTemplate}
                  data-testid={`btn-item-type-${t.value}`}
                  className={`h-5 px-1.5 text-[10px] rounded border font-medium transition-colors shrink-0 ${
                    itemAddType === t.value
                      ? t.color
                      : "border-border text-muted-foreground hover:bg-muted"
                  }`}
                >
                  {t.label}
                </button>
              ))}
            </>
          )}

          {fefoLoading && (
            <Badge variant="secondary" className="text-[10px] px-1.5 py-0 shrink-0">
              جاري توزيع الصلاحية...
            </Badge>
          )}
        </div>
      )}

      {/* ── جدول البنود الموحد ────────────────────────────────────────────────── */}
      <div className="overflow-x-auto border rounded-md" dir="rtl">
        <table className="peachtree-grid w-full text-sm">
          <thead>
            <tr className="peachtree-grid-header">
              <th className="text-center" style={{ width: 30 }}>#</th>
              <th className="text-center" style={{ width: 72 }}>النوع</th>
              <th>الوصف</th>
              <th className="text-center" style={{ width: 110 }}>الطبيب</th>
              <th className="text-center" style={{ width: 90 }}>الممرض</th>
              <th className="text-center" style={{ width: 76 }}>الوحدة</th>
              <th className="text-center" style={{ width: 76 }}>الكمية</th>
              <th className="text-center" style={{ width: 90 }}>سعر الوحدة</th>
              <th className="text-center" style={{ width: 70 }}>خصم %</th>
              <th className="text-center" style={{ width: 90 }}>قيمة الخصم</th>
              <th className="text-center" style={{ width: 100 }}>الإجمالي</th>
              {isDraft && <th className="text-center" style={{ width: 40 }}></th>}
            </tr>
          </thead>
          <tbody>
            {lines.map((line, i) => {
              const isService    = line.lineType === "service";
              const hasExpiry    = (line.lineType === "drug" || line.lineType === "consumable");
              const hasStatsBtn  = (line.lineType === "drug" || line.lineType === "consumable") && !!line.itemId;
              const isAutoLine   = isAutoGenerated(line);
              const rowClass = getInvoiceRowClass({
                isAutoLine,
                isOversellNoStock: isOversellRow(
                  line.lineType,
                  line.item?.allowOversell,
                  line.item?.availableQtyMinor,
                ),
              });

              return (
                <tr
                  key={line.tempId}
                  className={`peachtree-grid-row ${isService ? getServiceRowClass(line.serviceType) : ""} ${rowClass}`}
                  data-testid={`row-line-unified-${i}`}
                >
                  {/* # */}
                  <td className="text-center text-muted-foreground">{i + 1}</td>

                  {/* النوع */}
                  <td className="text-center">
                    <div className="flex flex-col items-center gap-0.5">
                      {getLineTypeBadge(line.lineType)}
                      {getBizClassBadge(line.businessClassification)}
                      {isAutoLine && (
                        <Badge variant="outline" className="text-[9px] px-1 py-0 text-sky-600 dark:text-sky-400 border-sky-300">
                          تلقائي
                        </Badge>
                      )}
                    </div>
                  </td>

                  {/* الوصف */}
                  <td>
                    {isDraft ? (
                      <div className="space-y-0.5">
                        <div className="flex flex-row-reverse items-center gap-1">
                          <Input
                            value={line.description}
                            onChange={(e) => updateLine(line.tempId, "description", e.target.value)}
                            className="h-7 text-xs flex-1"
                            data-testid={`input-desc-unified-${i}`}
                          />
                          {hasStatsBtn && (
                            <Button
                              variant="ghost" size="icon" className="h-7 w-7 shrink-0"
                              onClick={() => openStatsPopup(line.itemId!, line.description)}
                              data-testid={`button-stock-stats-unified-${i}`}
                            >
                              <BarChart3 className="h-3.5 w-3.5 text-muted-foreground" />
                            </Button>
                          )}
                        </div>
                        {hasExpiry && line.expiryMonth && line.expiryYear && (
                          <div className="flex flex-row-reverse items-center gap-1">
                            <Badge variant="secondary" className="text-[10px]">
                              {String(line.expiryMonth).padStart(2, "0")}/{line.expiryYear}
                            </Badge>
                            {line.priceSource === "department" && (
                              <Badge variant="secondary" className="text-[10px] bg-green-100 dark:bg-green-950/40 text-green-700 dark:text-green-400">
                                سعر القسم
                              </Badge>
                            )}
                          </div>
                        )}
                      </div>
                    ) : (
                      <div>
                        <div className="flex flex-row-reverse items-center gap-1">
                          <span className="text-xs">{line.description}</span>
                          {hasStatsBtn && (
                            <Button
                              variant="ghost" size="icon" className="h-6 w-6 shrink-0"
                              onClick={() => openStatsPopup(line.itemId!, line.description)}
                              data-testid={`button-stock-stats-ro-${i}`}
                            >
                              <BarChart3 className="h-3 w-3 text-muted-foreground" />
                            </Button>
                          )}
                        </div>
                        {hasExpiry && line.expiryMonth && line.expiryYear && (
                          <div className="flex flex-row-reverse items-center gap-1 mt-0.5">
                            <Badge variant="secondary" className="text-[10px]">
                              {String(line.expiryMonth).padStart(2, "0")}/{line.expiryYear}
                            </Badge>
                          </div>
                        )}
                        {line.coverageStatus && line.coverageStatus !== "not_required" && (
                          <TooltipProvider>
                            <div className="flex flex-row-reverse items-center gap-1 mt-0.5 flex-wrap">
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <span>
                                    {line.coverageStatus === "covered" ? (
                                      <Badge className="text-[10px] bg-green-100 dark:bg-green-950/40 text-green-700 dark:text-green-400 border-green-300 gap-0.5 cursor-help">
                                        <ShieldCheck className="h-2.5 w-2.5" />مشمول
                                      </Badge>
                                    ) : line.coverageStatus === "excluded" ? (
                                      <Badge className="text-[10px] bg-red-100 dark:bg-red-950/40 text-red-700 dark:text-red-400 border-red-300 gap-0.5 cursor-help">
                                        <ShieldOff className="h-2.5 w-2.5" />مستثنى
                                      </Badge>
                                    ) : (
                                      <Badge variant="secondary" className="text-[10px] gap-0.5 cursor-help">
                                        <ShieldCheck className="h-2.5 w-2.5" />{line.coverageStatus}
                                      </Badge>
                                    )}
                                  </span>
                                </TooltipTrigger>
                                <TooltipContent side="top" dir="rtl" className="max-w-xs text-xs leading-relaxed">
                                  {line.coverageStatus === "covered" && line.companyShareAmount && (
                                    <div>
                                      <span className="font-medium">نصيب الشركة: </span>
                                      {formatNumber(parseFloat(line.companyShareAmount || "0"))} ج.م
                                    </div>
                                  )}
                                </TooltipContent>
                              </Tooltip>
                              {line.approvalStatus === "pending" && (
                                <Badge className="text-[10px] bg-amber-100 dark:bg-amber-950/40 text-amber-700 dark:text-amber-400 border-amber-300 gap-0.5">
                                  <Clock className="h-2.5 w-2.5" />ينتظر موافقة
                                </Badge>
                              )}
                              {line.coverageStatus === "covered" && line.companyShareAmount && parseFloat(line.companyShareAmount) > 0 && (
                                <Badge variant="outline" className="text-[10px] text-blue-700 dark:text-blue-400 border-blue-300">
                                  شركة: {formatNumber(parseFloat(line.companyShareAmount))}
                                </Badge>
                              )}
                              {line.coverageStatus === "covered" && line.patientShareAmount && parseFloat(line.patientShareAmount) > 0 && (
                                <Badge variant="outline" className="text-[10px] text-orange-700 dark:text-orange-400 border-orange-300">
                                  مريض: {formatNumber(parseFloat(line.patientShareAmount))}
                                </Badge>
                              )}
                            </div>
                          </TooltipProvider>
                        )}
                      </div>
                    )}
                  </td>

                  {/* الطبيب — يظهر للخدمات التي تحتاجه */}
                  <td className={`text-center ${isService && line.requiresDoctor ? "bg-blue-50 dark:bg-blue-950/40" : ""}`}>
                    {isService && line.requiresDoctor ? (
                      isDraft ? (
                        <Input
                          value={line.doctorName}
                          onChange={(e) => updateLine(line.tempId, "doctorName", e.target.value)}
                          placeholder="اسم الطبيب *"
                          className={`h-7 text-xs ${!line.doctorName ? "border-blue-400 dark:border-blue-600" : ""}`}
                          data-testid={`input-doctor-unified-${i}`}
                        />
                      ) : (
                        <span className="text-xs">{line.doctorName || "-"}</span>
                      )
                    ) : (
                      <span className="text-xs text-muted-foreground">—</span>
                    )}
                  </td>

                  {/* الممرض — يظهر للخدمات التي تحتاجه */}
                  <td className={`text-center ${isService && line.requiresNurse ? "bg-purple-50 dark:bg-purple-950/40" : ""}`}>
                    {isService && line.requiresNurse ? (
                      isDraft ? (
                        <Input
                          value={line.nurseName}
                          onChange={(e) => updateLine(line.tempId, "nurseName", e.target.value)}
                          placeholder="اسم الممرض *"
                          className={`h-7 text-xs ${!line.nurseName ? "border-purple-400 dark:border-purple-600" : ""}`}
                          data-testid={`input-nurse-unified-${i}`}
                        />
                      ) : (
                        <span className="text-xs">{line.nurseName || "-"}</span>
                      )
                    ) : (
                      <span className="text-xs text-muted-foreground">—</span>
                    )}
                  </td>

                  {/* الوحدة — للأصناف فقط */}
                  <td className={`text-center ${
                    !isService && line.unitLevel === "medium"
                      ? "bg-orange-100 dark:bg-orange-900/30"
                      : !isService && line.unitLevel === "minor"
                      ? "bg-rose-100 dark:bg-rose-900/30"
                      : ""
                  }`}>
                    {!isService && line.itemId && line.item ? (
                      isDraft ? (
                        <select
                          value={line.unitLevel}
                          onChange={(e) => handleUnitLevelChange(line.tempId, e.target.value as "major" | "medium" | "minor")}
                          className={`peachtree-select w-full font-bold ${
                            line.unitLevel === "medium"
                              ? "border-orange-500 text-orange-800 dark:text-orange-200 bg-orange-50 dark:bg-orange-900/40"
                              : line.unitLevel === "minor"
                              ? "border-rose-500 text-rose-800 dark:text-rose-200 bg-rose-50 dark:bg-rose-900/40"
                              : ""
                          }`}
                          data-testid={`select-unit-unified-${i}`}
                        >
                          {getUnitOptions(line.item).map((opt) => (
                            <option
                              key={opt.value}
                              value={opt.value}
                              disabled={!opt.priceable}
                              title={!opt.priceable ? "معامل التحويل غير معرّف لهذه الوحدة — يجب إعداد الصنف أولاً" : undefined}
                            >
                              {opt.priceable ? opt.label : `${opt.label} (غير معرّف)`}
                            </option>
                          ))}
                        </select>
                      ) : (
                        <span className={`font-bold ${
                          line.unitLevel === "medium"
                            ? "text-orange-700 dark:text-orange-300"
                            : line.unitLevel === "minor"
                            ? "text-rose-700 dark:text-rose-300"
                            : "text-foreground font-normal"
                        }`} data-testid={`text-unit-unified-${i}`}>
                          {getUnitName(line.item, line.unitLevel)}
                        </span>
                      )
                    ) : (
                      <span className="text-xs text-muted-foreground">—</span>
                    )}
                  </td>

                  {/* الكمية */}
                  <td className="text-center">
                    {isDraft ? (
                      isAutoGenerated(line) ? (
                        /* STAY_ENGINE: عدد الأيام — مطلوب يدوياً */
                        <Input
                          type="number"
                          value={line.quantity === 0 ? "" : line.quantity}
                          min={1} step="1"
                          onChange={(e) => {
                            const days = parseFloat(e.target.value) || 0;
                            updateLine(line.tempId, "quantity", days);
                            updateLine(line.tempId, "totalPrice", +(days * line.unitPrice).toFixed(2));
                          }}
                          placeholder="الأيام"
                          className={`h-7 text-xs text-center ${line.quantity === 0 ? "border-amber-400 bg-amber-50 dark:bg-amber-950/20" : ""}`}
                          data-testid={`input-stay-days-${i}`}
                        />
                      ) : hasExpiry && line.lotId ? (
                        <Input
                          type="number"
                          defaultValue={line.quantity}
                          min={0} step="any"
                          onChange={(e) => pendingQtyRef.current.set(line.tempId, e.target.value)}
                          onBlur={() => handleQtyConfirm(line.tempId)}
                          onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); handleQtyConfirm(line.tempId); } }}
                          className="h-7 text-xs text-center"
                          data-testid={`input-qty-unified-${i}`}
                        />
                      ) : (
                        <Input
                          type="number"
                          value={line.quantity}
                          min={0} step="any"
                          onChange={(e) => updateLine(line.tempId, "quantity", parseFloat(e.target.value) || 0)}
                          className="h-7 text-xs text-center"
                          data-testid={`input-qty-unified-${i}`}
                        />
                      )
                    ) : (
                      <span className="text-xs">
                        {isAutoGenerated(line) && line.quantity === 0
                          ? <span className="text-amber-600 text-[10px]">— أيام —</span>
                          : formatNumber(line.quantity)}
                      </span>
                    )}
                  </td>

                  {/* سعر الوحدة — مغلق، يتحدد تلقائياً من الصنف أو القسم */}
                  <td className="text-center">
                    <span
                      className="flex items-center justify-center gap-0.5 peachtree-amount"
                      title="سعر النظام — يتحدد تلقائياً بناءً على الصنف أو القسم"
                      data-testid={`text-unit-price-unified-${i}`}
                    >
                      {isDraft && <Lock className="h-3 w-3 text-muted-foreground shrink-0" />}
                      {formatNumber(line.unitPrice)}
                    </span>
                  </td>

                  {/* خصم % */}
                  <td className="text-center">
                    {isDraft ? (
                      <Input
                        type="number"
                        value={line.discountPercent}
                        min={0} max={100}
                        onChange={(e) => updateLine(line.tempId, "discountPercent", parseFloat(e.target.value) || 0)}
                        className="h-7 text-xs text-center"
                        data-testid={`input-disc-pct-unified-${i}`}
                      />
                    ) : (
                      <span className="text-xs">{formatNumber(line.discountPercent)}</span>
                    )}
                  </td>

                  {/* قيمة الخصم */}
                  <td className="text-center">
                    {isDraft ? (
                      <Input
                        type="number"
                        value={line.discountAmount}
                        min={0}
                        onChange={(e) => updateLine(line.tempId, "discountAmount", parseFloat(e.target.value) || 0)}
                        className="h-7 text-xs text-center"
                        data-testid={`input-disc-amt-unified-${i}`}
                      />
                    ) : (
                      <span className="text-xs">{formatNumber(line.discountAmount)}</span>
                    )}
                  </td>

                  {/* الإجمالي */}
                  <td className="text-center font-bold text-xs">{formatNumber(line.totalPrice)}</td>

                  {/* حذف */}
                  {isDraft && (
                    <td className="text-center">
                      <Button
                        variant="ghost" size="icon"
                        onClick={() => removeLine(line.tempId)}
                        data-testid={`button-remove-line-unified-${i}`}
                      >
                        <X className="h-3 w-3 text-destructive" />
                      </Button>
                    </td>
                  )}
                </tr>
              );
            })}
            {lines.length === 0 && (
              <tr>
                <td colSpan={colSpanFull} className="text-center text-muted-foreground py-6 text-sm">
                  لا توجد بنود — أضف خدمة أو صنف باستخدام أزرار الإضافة أعلاه
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* ملخص عدد البنود حسب النوع */}
      {lines.length > 0 && (
        <div className="flex flex-row-reverse flex-wrap gap-2 text-xs text-muted-foreground">
          {(["service", "drug", "consumable", "equipment"] as KnownLineType[])
            .map(t => {
              const count = lines.filter(l => l.lineType === t).length;
              if (!count) return null;
              const cfg = LINE_TYPE_CONFIG[t];
              return (
                <Badge key={t} variant="outline" className={`text-[10px] px-2 ${cfg.className}`}>
                  {cfg.label}: {count}
                </Badge>
              );
            })}
          <span className="mr-auto">إجمالي البنود: {lines.length}</span>
        </div>
      )}

      {/* ── ItemFastSearch modal ────────────────────────────────────────────── */}
      {fastSearchOpen && (
        <ItemFastSearch
          open={fastSearchOpen}
          onClose={() => setFastSearchOpen(false)}
          warehouseId={warehouseId}
          invoiceDate={invoiceDate || new Date().toISOString().split("T")[0]}
          onItemSelected={handleFastItemSelected}
          title="بحث سريع — أضف صنف للفاتورة"
        />
      )}
    </div>
  );
}
