import { useState, useEffect, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Loader2, FileText, Search as SearchIcon } from "lucide-react";
import { ItemFastSearch } from "@/components/ItemFastSearch/ItemFastSearch";
import type { ItemSelectedPayload } from "@/components/ItemFastSearch/types";
import type { ItemSearchResult } from "../hooks/useLineManagement";
import { useQuery } from "@tanstack/react-query";
import type { InvoiceTemplate } from "@shared/schema";
import type { Service, Item } from "@shared/schema";
import type { LineLocal } from "../types";
import { ServiceLookup } from "@/components/lookups";
import { InvoiceLineRow } from "./InvoiceLineRow";

// ── نوع البند — ألوان وتسميات (للـ footer فقط) ───────────────────────────────
type KnownLineType = "service" | "drug" | "consumable" | "equipment";

const LINE_TYPE_CONFIG: Record<KnownLineType, { label: string; className: string }> = {
  service:    { label: "خدمة",    className: "bg-blue-100 text-blue-700 dark:bg-blue-950/50 dark:text-blue-400 border-blue-300" },
  drug:       { label: "دواء",    className: "bg-green-100 text-green-700 dark:bg-green-950/50 dark:text-green-400 border-green-300" },
  consumable: { label: "مستهلك", className: "bg-orange-100 text-orange-700 dark:bg-orange-950/50 dark:text-orange-400 border-orange-300" },
  equipment:  { label: "جهاز",   className: "bg-purple-100 text-purple-700 dark:bg-purple-950/50 dark:text-purple-400 border-purple-300" },
};

// NOTE: isExpiryNear, getLineTypeBadge, getBizClassBadge, isAutoGenerated
//       are all defined inside InvoiceLineRow.tsx (self-contained).

// ── نوع الصنف المختار للإضافة ──────────────────────────────────────────────────
type ItemAddType = "drug" | "consumable" | "equipment";
const ITEM_ADD_TYPES: { value: ItemAddType; label: string; color: string }[] = [
  { value: "drug",       label: "دواء",    color: "bg-green-100 text-green-700 border-green-300 dark:bg-green-950/50 dark:text-green-400" },
  { value: "consumable", label: "مستهلك",  color: "bg-orange-100 text-orange-700 border-orange-300 dark:bg-orange-950/50 dark:text-orange-400" },
  { value: "equipment",  label: "جهاز",   color: "bg-purple-100 text-purple-700 border-purple-300 dark:bg-purple-950/50 dark:text-purple-400" },
];

// نحوّل category الصنف → lineType (مع دعم gas وservice)
function categoryToLineType(category: string | null | undefined, fallback: ItemAddType): ItemAddType {
  switch (category) {
    case "drug":        return "drug";
    case "equipment":   return "equipment";
    case "gas":         return "consumable";  // الغاز → مستهلك
    case "consumable":  return "consumable";
    default:            return fallback;
  }
}

interface UnifiedLinesTabProps {
  lines: LineLocal[];
  isDraft: boolean;

  // Item search state — kept for back-compat but no longer used in UI (ItemFastSearch handles search)
  itemSearch?: string;
  setItemSearch?: (v: string) => void;
  setItemResults?: (v: Item[]) => void;
  itemResults?: Item[];
  searchingItems?: boolean;
  fefoLoading: boolean;
  itemSearchRef?: React.RefObject<HTMLInputElement>;
  itemDropdownRef?: React.RefObject<HTMLDivElement>;
  pendingQtyRef?: React.MutableRefObject<Map<string, string>>;

  // Mutation functions
  addServiceLine: (svc: Service) => void | Promise<void>;
  addItemLine: (item: Item, type: ItemAddType) => void;
  updateLine: (tempId: string, field: string, value: unknown) => void;
  removeLine: (tempId: string) => void;
  handleQtyConfirm: (tempId: string) => void;
  handleUnitLevelChange: (tempId: string, level: "major" | "medium" | "minor") => void;
  openStatsPopup: (itemId: string, name: string) => void;
  getServiceRowClass: (serviceType: string) => string;
  applyTemplate?: (templateId: string, opts?: { replaceExisting?: boolean }) => Promise<void>;
  // For ItemFastSearch
  warehouseId?: string;
  invoiceDate?: string;
  // لتصفية الخدمات بالقسم في ServiceLookup
  departmentId?: string;
}

export function UnifiedLinesTab({
  lines,
  isDraft,
  itemSearch, setItemSearch, setItemResults, itemResults, searchingItems, fefoLoading,
  itemSearchRef, itemDropdownRef, pendingQtyRef,
  addServiceLine, addItemLine, updateLine, removeLine,
  handleQtyConfirm, handleUnitLevelChange, openStatsPopup, getServiceRowClass,
  applyTemplate,
  warehouseId = "",
  invoiceDate,
  departmentId,
}: UnifiedLinesTabProps) {
  const [sourceMode, setSourceMode] = useState<"service" | "item">("service");
  const [itemAddType, setItemAddType] = useState<ItemAddType>("drug");
  const [fastSearchOpen, setFastSearchOpen] = useState(false);

  // F2 shortcut to open ItemFastSearch
  useEffect(() => {
    function handleKeyDown(e: KeyboardEvent) {
      if (e.key === "F2" && isDraft && !fastSearchOpen) {
        e.preventDefault();
        setSourceMode("item");
        setFastSearchOpen(true);
      }
    }
    document.addEventListener("keydown", handleKeyDown);
    return () => document.removeEventListener("keydown", handleKeyDown);
  }, [isDraft, fastSearchOpen]);

  // Adapter: FastSearchItem → ItemSearchResult → addItemLine
  const handleFastItemSelected = useCallback((payload: ItemSelectedPayload) => {
    const { item } = payload;
    const adapted: ItemSearchResult = {
      id: item.id,
      nameAr: item.nameAr,
      itemCode: item.itemCode,
      hasExpiry: item.hasExpiry,
      allowOversell: item.allowOversell ?? null,
      availableQtyMinor: item.availableQtyMinor,
      salePriceCurrent: item.salePriceCurrent,
      purchasePriceLast: undefined,
      businessClassification: undefined,
      majorUnitName: item.majorUnitName,
      mediumUnitName: item.mediumUnitName,
      minorUnitName: item.minorUnitName,
      majorToMedium: item.majorToMedium ? Number(item.majorToMedium) : null,
      majorToMinor:  item.majorToMinor  ? Number(item.majorToMinor)  : null,
      mediumToMinor: item.mediumToMinor ? Number(item.mediumToMinor) : null,
    };
    // تحديد النوع تلقائياً من category الصنف (دواء / مستهلك / جهاز / غاز)
    const lineType = categoryToLineType(item.category, itemAddType);
    addItemLine(adapted as unknown as Item, lineType);
    setFastSearchOpen(false);
  }, [addItemLine, itemAddType]);
  const [selectedServiceId, setSelectedServiceId] = useState("");
  const [selectedTemplateId, setSelectedTemplateId] = useState("__none__");
  const [applyingTemplate, setApplyingTemplate] = useState(false);
  const [replaceExisting, setReplaceExisting] = useState(false);

  const { data: templates } = useQuery<InvoiceTemplate[]>({
    queryKey: ["/api/invoice-templates"],
    enabled: isDraft && !!applyTemplate,
  });

  async function handleApplyTemplate() {
    if (!applyTemplate || !selectedTemplateId || selectedTemplateId === "__none__") return;
    setApplyingTemplate(true);
    try {
      await applyTemplate(selectedTemplateId, { replaceExisting });
      setSelectedTemplateId("__none__");
    } finally {
      setApplyingTemplate(false);
    }
  }

  const colSpanFull = isDraft ? 12 : 11;

  return (
    <div className="space-y-2">

      {/* ══ شريط إضافة البنود (سطر واحد مضغوط) ════════════════════════════════ */}
      {isDraft && (
        <div className="flex items-center gap-1.5 border rounded-md px-2 py-1 bg-muted/20 flex-wrap" dir="rtl">

          {/* ── نموذج (إذا وُجد) ─────────────────── */}
          {applyTemplate && templates && templates.length > 0 && (
            <>
              <FileText className="h-3 w-3 text-muted-foreground shrink-0" />
              <Select value={selectedTemplateId} onValueChange={setSelectedTemplateId} disabled={applyingTemplate}>
                <SelectTrigger className="h-6 text-[11px] w-36 px-1" data-testid="select-template">
                  <SelectValue placeholder="نموذج..." />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="__none__">— نموذج —</SelectItem>
                  {templates.map(t => (
                    <SelectItem key={t.id} value={t.id}>{t.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <Button
                size="sm"
                variant="secondary"
                className="h-6 text-[11px] px-2 shrink-0"
                onClick={handleApplyTemplate}
                disabled={selectedTemplateId === "__none__" || applyingTemplate}
                data-testid="btn-apply-template"
              >
                {applyingTemplate ? <Loader2 className="h-3 w-3 animate-spin" /> : "تطبيق"}
              </Button>
              <label className="flex items-center gap-1 cursor-pointer shrink-0" data-testid="toggle-replace-existing">
                <input
                  type="checkbox"
                  checked={replaceExisting}
                  onChange={e => setReplaceExisting(e.target.checked)}
                  disabled={applyingTemplate}
                  className="h-3 w-3 accent-primary"
                />
                <span className="text-[10px] text-muted-foreground">استبدال</span>
              </label>
              <div className="w-px h-4 bg-border/50 shrink-0" />
            </>
          )}

          {/* ── مفتاح المصدر: خدمة / صنف ───────── */}
          <span className="text-[10px] text-muted-foreground shrink-0">إضافة:</span>
          <div className="flex gap-0.5 shrink-0">
            <button
              type="button"
              onClick={() => setSourceMode("service")}
              data-testid="btn-source-service"
              className={`h-6 px-2.5 text-[11px] rounded border font-medium transition-colors ${
                sourceMode === "service"
                  ? "bg-primary text-primary-foreground border-primary"
                  : "border-border text-muted-foreground hover:bg-muted"
              }`}
            >
              خدمة
            </button>
            <button
              type="button"
              onClick={() => setSourceMode("item")}
              data-testid="btn-source-item"
              className={`h-6 px-2.5 text-[11px] rounded border font-medium transition-colors ${
                sourceMode === "item"
                  ? "bg-primary text-primary-foreground border-primary"
                  : "border-border text-muted-foreground hover:bg-muted"
              }`}
            >
              صنف
            </button>
          </div>

          {/* ── بحث عن خدمة ─────────────────────── */}
          {sourceMode === "service" && (
            <div className="flex-1 min-w-[180px]">
              <ServiceLookup
                value={selectedServiceId}
                onChange={(item) => {
                  if (item) {
                    addServiceLine(item.meta as Service);
                    setSelectedServiceId("");
                  }
                }}
                departmentId={departmentId || undefined}
                placeholder="بحث عن خدمة..."
                disabled={!isDraft || applyingTemplate}
                data-testid="input-service-search-unified"
              />
            </div>
          )}

          {/* ── بحث عن صنف (F2 modal) ─────────── */}
          {sourceMode === "item" && (
            <>
              <Button
                size="sm"
                variant="default"
                className="h-6 text-[11px] px-3 gap-1 shrink-0"
                onClick={() => setFastSearchOpen(true)}
                disabled={!isDraft || applyingTemplate || !warehouseId}
                data-testid="btn-open-item-fast-search"
              >
                <SearchIcon className="h-3 w-3" />
                بحث صنف
                <kbd className="text-[8px] bg-white/20 px-0.5 rounded border border-white/30">F2</kbd>
              </Button>
              {/* نوع احتياطي */}
              <span className="text-[9px] text-muted-foreground shrink-0">نوع احتياطي:</span>
              {ITEM_ADD_TYPES.map(t => (
                <button
                  key={t.value}
                  type="button"
                  onClick={() => setItemAddType(t.value)}
                  disabled={!isDraft || applyingTemplate}
                  data-testid={`btn-item-type-${t.value}`}
                  className={`h-5 px-1.5 text-[10px] rounded border font-medium transition-colors shrink-0 ${
                    itemAddType === t.value
                      ? t.color
                      : "border-border text-muted-foreground hover:bg-muted"
                  }`}
                >
                  {t.label}
                </button>
              ))}
            </>
          )}

          {fefoLoading && (
            <Badge variant="secondary" className="text-[10px] px-1.5 py-0 shrink-0">
              جاري توزيع الصلاحية...
            </Badge>
          )}
        </div>
      )}

      {/* ── جدول البنود الموحد ────────────────────────────────────────────────── */}
      <div className="overflow-x-auto border rounded-md" dir="rtl">
        <table className="peachtree-grid w-full text-sm">
          <thead>
            <tr className="peachtree-grid-header">
              <th className="text-center" style={{ width: 30 }}>#</th>
              <th className="text-center" style={{ width: 72 }}>النوع</th>
              <th>الوصف</th>
              <th className="text-center" style={{ width: 110 }}>الطبيب</th>
              <th className="text-center" style={{ width: 90 }}>الممرض</th>
              <th className="text-center" style={{ width: 76 }}>الوحدة</th>
              <th className="text-center" style={{ width: 76 }}>الكمية</th>
              <th className="text-center" style={{ width: 80 }}>الصلاحية</th>
              <th className="text-center" style={{ width: 90 }}>سعر الوحدة</th>
              <th className="text-center" style={{ width: 70 }}>خصم %</th>
              <th className="text-center" style={{ width: 90 }}>قيمة الخصم</th>
              <th className="text-center" style={{ width: 100 }}>الإجمالي</th>
              {isDraft && <th className="text-center" style={{ width: 40 }}></th>}
            </tr>
          </thead>
          <tbody>
            {lines.map((line, i) => (
              <InvoiceLineRow
                key={line.tempId}
                line={line}
                index={i}
                isDraft={isDraft}
                updateLine={updateLine}
                removeLine={removeLine}
                handleQtyConfirm={handleQtyConfirm}
                handleUnitLevelChange={handleUnitLevelChange}
                openStatsPopup={openStatsPopup}
                getServiceRowClass={getServiceRowClass}
                pendingQtyRef={pendingQtyRef}
              />
            ))}
            {lines.length === 0 && (
              <tr>
                <td colSpan={colSpanFull} className="text-center text-muted-foreground py-6 text-sm">
                  لا توجد بنود — أضف خدمة أو صنف باستخدام أزرار الإضافة أعلاه
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* ملخص عدد البنود حسب النوع */}
      {lines.length > 0 && (
        <div className="flex flex-row-reverse flex-wrap gap-2 text-xs text-muted-foreground">
          {(["service", "drug", "consumable", "equipment"] as KnownLineType[])
            .map(t => {
              const count = lines.filter(l => l.lineType === t).length;
              if (!count) return null;
              const cfg = LINE_TYPE_CONFIG[t];
              return (
                <Badge key={t} variant="outline" className={`text-[10px] px-2 ${cfg.className}`}>
                  {cfg.label}: {count}
                </Badge>
              );
            })}
          <span className="mr-auto">إجمالي البنود: {lines.length}</span>
        </div>
      )}

      {/* ── ItemFastSearch modal ────────────────────────────────────────────── */}
      {fastSearchOpen && (
        <ItemFastSearch
          open={fastSearchOpen}
          onClose={() => setFastSearchOpen(false)}
          warehouseId={warehouseId}
          invoiceDate={invoiceDate || new Date().toISOString().split("T")[0]}
          onItemSelected={handleFastItemSelected}
          title="بحث سريع — أضف صنف للفاتورة"
        />
      )}
    </div>
  );
}
