import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { Loader2, X, BarChart3, ShieldCheck, ShieldOff, Clock } from "lucide-react";
import { formatNumber } from "@/lib/formatters";
import type { Service, Item } from "@shared/schema";
import type { LineLocal } from "../types";
import {
  itemHasMajorUnit,
  itemHasMediumUnit,
  getUnitName,
} from "../utils/units";
import { SearchDropdown } from "./SearchDropdown";
import { ServiceLookup } from "@/components/lookups";

// ── نوع البند — مخطط الألوان والتسميات ────────────────────────────────────────
type KnownLineType = "service" | "drug" | "consumable" | "equipment";

const LINE_TYPE_CONFIG: Record<KnownLineType, { label: string; className: string }> = {
  service:    { label: "خدمة",    className: "bg-blue-100 text-blue-700 dark:bg-blue-950/50 dark:text-blue-400 border-blue-300" },
  drug:       { label: "دواء",    className: "bg-green-100 text-green-700 dark:bg-green-950/50 dark:text-green-400 border-green-300" },
  consumable: { label: "مستهلك", className: "bg-orange-100 text-orange-700 dark:bg-orange-950/50 dark:text-orange-400 border-orange-300" },
  equipment:  { label: "جهاز",   className: "bg-purple-100 text-purple-700 dark:bg-purple-950/50 dark:text-purple-400 border-purple-300" },
};

function getLineTypeBadge(lineType: string) {
  const cfg = LINE_TYPE_CONFIG[lineType as KnownLineType];
  if (!cfg) return <Badge variant="outline" className="text-[10px] px-1">{lineType}</Badge>;
  return (
    <Badge variant="outline" className={`text-[10px] px-1.5 py-0 font-medium ${cfg.className}`}>
      {cfg.label}
    </Badge>
  );
}

// ── Stay Engine badge ──────────────────────────────────────────────────────────
function isAutoGenerated(line: LineLocal): boolean {
  return line.sourceType === "stay_engine" || line.priceSource === "stay_engine";
}

// ── نوع الصنف المختار للإضافة ──────────────────────────────────────────────────
type ItemAddType = "drug" | "consumable" | "equipment";
const ITEM_ADD_TYPES: { value: ItemAddType; label: string }[] = [
  { value: "drug",       label: "دواء" },
  { value: "consumable", label: "مستهلك" },
  { value: "equipment",  label: "جهاز" },
];

interface UnifiedLinesTabProps {
  lines: LineLocal[];
  isDraft: boolean;

  // Item search state (shared from parent)
  itemSearch: string;
  setItemSearch: (v: string) => void;
  setItemResults: (v: Item[]) => void;
  itemResults: Item[];
  searchingItems: boolean;
  fefoLoading: boolean;
  itemSearchRef: React.RefObject<HTMLInputElement>;
  itemDropdownRef: React.RefObject<HTMLDivElement>;
  pendingQtyRef: React.MutableRefObject<Map<string, string>>;

  // Mutation functions
  addServiceLine: (svc: Service) => void;
  addItemLine: (item: Item, type: ItemAddType) => void;
  updateLine: (tempId: string, field: string, value: unknown) => void;
  removeLine: (tempId: string) => void;
  handleQtyConfirm: (tempId: string) => void;
  handleUnitLevelChange: (tempId: string, level: "major" | "medium" | "minor") => void;
  openStatsPopup: (itemId: string, name: string) => void;
  getServiceRowClass: (serviceType: string) => string;
}

export function UnifiedLinesTab({
  lines,
  isDraft,
  itemSearch, setItemSearch, setItemResults, itemResults, searchingItems, fefoLoading,
  itemSearchRef, itemDropdownRef, pendingQtyRef,
  addServiceLine, addItemLine, updateLine, removeLine,
  handleQtyConfirm, handleUnitLevelChange, openStatsPopup, getServiceRowClass,
}: UnifiedLinesTabProps) {
  const [sourceMode, setSourceMode] = useState<"service" | "item">("service");
  const [itemAddType, setItemAddType] = useState<ItemAddType>("drug");
  const [selectedServiceId, setSelectedServiceId] = useState("");

  const colSpanFull = isDraft ? 12 : 11;

  return (
    <div className="space-y-3">

      {/* ── منطقة إضافة البند ─────────────────────────────────────────────────── */}
      {isDraft && (
        <div className="space-y-2 border rounded-md p-2 bg-muted/20">
          {/* مفتاح المصدر */}
          <div className="flex flex-row-reverse items-center gap-1">
            <span className="text-xs text-muted-foreground ml-2">نوع البند:</span>
            <div className="flex gap-1">
              <Button
                size="sm"
                variant={sourceMode === "service" ? "default" : "outline"}
                className="h-7 text-xs px-3"
                onClick={() => setSourceMode("service")}
                data-testid="btn-source-service"
              >
                خدمة
              </Button>
              <Button
                size="sm"
                variant={sourceMode === "item" ? "default" : "outline"}
                className="h-7 text-xs px-3"
                onClick={() => setSourceMode("item")}
                data-testid="btn-source-item"
              >
                صنف
              </Button>
            </div>
          </div>

          {/* إضافة خدمة */}
          {sourceMode === "service" && (
            <div className="flex flex-row-reverse items-center gap-2">
              <div className="flex-1 min-w-[200px]">
                <ServiceLookup
                  value={selectedServiceId}
                  onChange={(item) => {
                    if (item) {
                      addServiceLine(item.meta as Service);
                      setSelectedServiceId("");
                    }
                  }}
                  placeholder="بحث عن خدمة..."
                  disabled={!isDraft}
                  data-testid="input-service-search-unified"
                />
              </div>
            </div>
          )}

          {/* إضافة صنف */}
          {sourceMode === "item" && (
            <div className="flex flex-row-reverse items-center gap-2 flex-wrap">
              {/* نوع الصنف */}
              <div className="flex gap-1 shrink-0">
                {ITEM_ADD_TYPES.map(t => (
                  <Button
                    key={t.value}
                    size="sm"
                    variant={itemAddType === t.value ? "secondary" : "ghost"}
                    className={`h-7 text-xs px-2 border ${
                      itemAddType === t.value
                        ? LINE_TYPE_CONFIG[t.value].className
                        : ""
                    }`}
                    onClick={() => setItemAddType(t.value)}
                    data-testid={`btn-item-type-${t.value}`}
                  >
                    {t.label}
                  </Button>
                ))}
              </div>
              {/* حقل البحث */}
              <div className="flex-1 min-w-[200px]">
                <SearchDropdown
                  inputRef={itemSearchRef}
                  dropdownRef={itemDropdownRef}
                  value={itemSearch}
                  onChange={setItemSearch}
                  onClear={() => { setItemSearch(""); setItemResults([]); }}
                  show={itemResults.length > 0}
                  setShow={(v) => { if (!v) setItemResults([]); }}
                  loading={false}
                  items={itemResults.map((item) => ({
                    id: item.id,
                    primary: item.nameAr || (item as any).itemCode || "",
                    raw: item,
                  }))}
                  onSelect={(si) => addItemLine(si.raw, itemAddType)}
                  placeholder="بحث عن صنف... (استخدم % للبحث المتقدم)"
                  disabled={!isDraft}
                  showSearchIcon
                  inputClassName="pr-8"
                  inputTestId={`input-item-search-unified`}
                  itemTestIdPrefix={`result-item-unified`}
                  renderItem={(si) => {
                    const item = si.raw as Item & {
                      itemCode?: string;
                      majorUnitName?: string;
                      salePriceCurrent?: number;
                      purchasePriceLast?: number;
                    };
                    return (
                      <div className="flex flex-row-reverse items-center justify-between gap-2 w-full">
                        <div className="flex flex-row-reverse items-center gap-2">
                          <span className="text-sm">{item.nameAr || item.itemCode}</span>
                          {item.itemCode && (
                            <span className="text-[10px] text-muted-foreground">({item.itemCode})</span>
                          )}
                        </div>
                        <span className="text-xs text-muted-foreground">
                          {formatNumber((item as any).salePriceCurrent || (item as any).purchasePriceLast || 0)}
                        </span>
                      </div>
                    );
                  }}
                />
              </div>
              {searchingItems && <Loader2 className="h-4 w-4 animate-spin shrink-0" />}
              {fefoLoading && <Badge variant="secondary" className="text-xs shrink-0">جاري توزيع الصلاحية...</Badge>}
            </div>
          )}
        </div>
      )}

      {/* ── جدول البنود الموحد ────────────────────────────────────────────────── */}
      <div className="overflow-x-auto border rounded-md">
        <table className="peachtree-grid w-full text-sm">
          <thead>
            <tr className="peachtree-grid-header">
              <th className="text-center" style={{ width: 30 }}>#</th>
              <th className="text-center" style={{ width: 72 }}>النوع</th>
              <th>الوصف</th>
              <th className="text-center" style={{ width: 110 }}>الطبيب</th>
              <th className="text-center" style={{ width: 90 }}>الممرض</th>
              <th className="text-center" style={{ width: 76 }}>الوحدة</th>
              <th className="text-center" style={{ width: 76 }}>الكمية</th>
              <th className="text-center" style={{ width: 90 }}>سعر الوحدة</th>
              <th className="text-center" style={{ width: 70 }}>خصم %</th>
              <th className="text-center" style={{ width: 90 }}>قيمة الخصم</th>
              <th className="text-center" style={{ width: 100 }}>الإجمالي</th>
              {isDraft && <th className="text-center" style={{ width: 40 }}></th>}
            </tr>
          </thead>
          <tbody>
            {lines.map((line, i) => {
              const isService    = line.lineType === "service";
              const hasExpiry    = (line.lineType === "drug" || line.lineType === "consumable");
              const hasStatsBtn  = (line.lineType === "drug" || line.lineType === "consumable") && !!line.itemId;
              const isAutoLine   = isAutoGenerated(line);

              return (
                <tr
                  key={line.tempId}
                  className={`peachtree-grid-row ${isService ? getServiceRowClass(line.serviceType) : ""} ${isAutoLine ? "bg-sky-50/50 dark:bg-sky-950/20" : ""}`}
                  data-testid={`row-line-unified-${i}`}
                >
                  {/* # */}
                  <td className="text-center text-muted-foreground">{i + 1}</td>

                  {/* النوع */}
                  <td className="text-center">
                    <div className="flex flex-col items-center gap-0.5">
                      {getLineTypeBadge(line.lineType)}
                      {isAutoLine && (
                        <Badge variant="outline" className="text-[9px] px-1 py-0 text-sky-600 dark:text-sky-400 border-sky-300">
                          تلقائي
                        </Badge>
                      )}
                    </div>
                  </td>

                  {/* الوصف */}
                  <td>
                    {isDraft ? (
                      <div className="space-y-0.5">
                        <div className="flex flex-row-reverse items-center gap-1">
                          <Input
                            value={line.description}
                            onChange={(e) => updateLine(line.tempId, "description", e.target.value)}
                            className="h-7 text-xs flex-1"
                            data-testid={`input-desc-unified-${i}`}
                          />
                          {hasStatsBtn && (
                            <Button
                              variant="ghost" size="icon" className="h-7 w-7 shrink-0"
                              onClick={() => openStatsPopup(line.itemId!, line.description)}
                              data-testid={`button-stock-stats-unified-${i}`}
                            >
                              <BarChart3 className="h-3.5 w-3.5 text-muted-foreground" />
                            </Button>
                          )}
                        </div>
                        {hasExpiry && line.expiryMonth && line.expiryYear && (
                          <div className="flex flex-row-reverse items-center gap-1">
                            <Badge variant="secondary" className="text-[10px]">
                              {String(line.expiryMonth).padStart(2, "0")}/{line.expiryYear}
                            </Badge>
                            {line.priceSource === "department" && (
                              <Badge variant="secondary" className="text-[10px] bg-green-100 dark:bg-green-950/40 text-green-700 dark:text-green-400">
                                سعر القسم
                              </Badge>
                            )}
                          </div>
                        )}
                      </div>
                    ) : (
                      <div>
                        <div className="flex flex-row-reverse items-center gap-1">
                          <span className="text-xs">{line.description}</span>
                          {hasStatsBtn && (
                            <Button
                              variant="ghost" size="icon" className="h-6 w-6 shrink-0"
                              onClick={() => openStatsPopup(line.itemId!, line.description)}
                              data-testid={`button-stock-stats-ro-${i}`}
                            >
                              <BarChart3 className="h-3 w-3 text-muted-foreground" />
                            </Button>
                          )}
                        </div>
                        {hasExpiry && line.expiryMonth && line.expiryYear && (
                          <div className="flex flex-row-reverse items-center gap-1 mt-0.5">
                            <Badge variant="secondary" className="text-[10px]">
                              {String(line.expiryMonth).padStart(2, "0")}/{line.expiryYear}
                            </Badge>
                          </div>
                        )}
                        {line.coverageStatus && line.coverageStatus !== "not_required" && (
                          <TooltipProvider>
                            <div className="flex flex-row-reverse items-center gap-1 mt-0.5 flex-wrap">
                              <Tooltip>
                                <TooltipTrigger asChild>
                                  <span>
                                    {line.coverageStatus === "covered" ? (
                                      <Badge className="text-[10px] bg-green-100 dark:bg-green-950/40 text-green-700 dark:text-green-400 border-green-300 gap-0.5 cursor-help">
                                        <ShieldCheck className="h-2.5 w-2.5" />مشمول
                                      </Badge>
                                    ) : line.coverageStatus === "excluded" ? (
                                      <Badge className="text-[10px] bg-red-100 dark:bg-red-950/40 text-red-700 dark:text-red-400 border-red-300 gap-0.5 cursor-help">
                                        <ShieldOff className="h-2.5 w-2.5" />مستثنى
                                      </Badge>
                                    ) : (
                                      <Badge variant="secondary" className="text-[10px] gap-0.5 cursor-help">
                                        <ShieldCheck className="h-2.5 w-2.5" />{line.coverageStatus}
                                      </Badge>
                                    )}
                                  </span>
                                </TooltipTrigger>
                                <TooltipContent side="top" dir="rtl" className="max-w-xs text-xs leading-relaxed">
                                  {line.coverageStatus === "covered" && line.companyShareAmount && (
                                    <div>
                                      <span className="font-medium">نصيب الشركة: </span>
                                      {formatNumber(parseFloat(line.companyShareAmount || "0"))} ج.م
                                    </div>
                                  )}
                                </TooltipContent>
                              </Tooltip>
                              {line.approvalStatus === "pending" && (
                                <Badge className="text-[10px] bg-amber-100 dark:bg-amber-950/40 text-amber-700 dark:text-amber-400 border-amber-300 gap-0.5">
                                  <Clock className="h-2.5 w-2.5" />ينتظر موافقة
                                </Badge>
                              )}
                              {line.coverageStatus === "covered" && line.companyShareAmount && parseFloat(line.companyShareAmount) > 0 && (
                                <Badge variant="outline" className="text-[10px] text-blue-700 dark:text-blue-400 border-blue-300">
                                  شركة: {formatNumber(parseFloat(line.companyShareAmount))}
                                </Badge>
                              )}
                              {line.coverageStatus === "covered" && line.patientShareAmount && parseFloat(line.patientShareAmount) > 0 && (
                                <Badge variant="outline" className="text-[10px] text-orange-700 dark:text-orange-400 border-orange-300">
                                  مريض: {formatNumber(parseFloat(line.patientShareAmount))}
                                </Badge>
                              )}
                            </div>
                          </TooltipProvider>
                        )}
                      </div>
                    )}
                  </td>

                  {/* الطبيب — يظهر للخدمات التي تحتاجه */}
                  <td className={`text-center ${isService && line.requiresDoctor ? "bg-blue-50 dark:bg-blue-950/40" : ""}`}>
                    {isService && line.requiresDoctor ? (
                      isDraft ? (
                        <Input
                          value={line.doctorName}
                          onChange={(e) => updateLine(line.tempId, "doctorName", e.target.value)}
                          placeholder="اسم الطبيب *"
                          className={`h-7 text-xs ${!line.doctorName ? "border-blue-400 dark:border-blue-600" : ""}`}
                          data-testid={`input-doctor-unified-${i}`}
                        />
                      ) : (
                        <span className="text-xs">{line.doctorName || "-"}</span>
                      )
                    ) : (
                      <span className="text-xs text-muted-foreground">—</span>
                    )}
                  </td>

                  {/* الممرض — يظهر للخدمات التي تحتاجه */}
                  <td className={`text-center ${isService && line.requiresNurse ? "bg-purple-50 dark:bg-purple-950/40" : ""}`}>
                    {isService && line.requiresNurse ? (
                      isDraft ? (
                        <Input
                          value={line.nurseName}
                          onChange={(e) => updateLine(line.tempId, "nurseName", e.target.value)}
                          placeholder="اسم الممرض *"
                          className={`h-7 text-xs ${!line.nurseName ? "border-purple-400 dark:border-purple-600" : ""}`}
                          data-testid={`input-nurse-unified-${i}`}
                        />
                      ) : (
                        <span className="text-xs">{line.nurseName || "-"}</span>
                      )
                    ) : (
                      <span className="text-xs text-muted-foreground">—</span>
                    )}
                  </td>

                  {/* الوحدة — للأصناف فقط */}
                  <td className="text-center">
                    {!isService && line.itemId && line.item ? (
                      isDraft ? (
                        <select
                          value={line.unitLevel}
                          onChange={(e) => handleUnitLevelChange(line.tempId, e.target.value as "major" | "medium" | "minor")}
                          className="h-7 text-xs text-center bg-transparent border rounded px-1 w-full"
                          data-testid={`select-unit-unified-${i}`}
                        >
                          {itemHasMajorUnit(line.item) && (
                            <option value="major">{line.item?.majorUnitName || "كبرى"}</option>
                          )}
                          {itemHasMediumUnit(line.item) && (
                            <option value="medium">{line.item?.mediumUnitName || "متوسطة"}</option>
                          )}
                          {(line.item?.minorUnitName || (!itemHasMajorUnit(line.item) && !itemHasMediumUnit(line.item))) && (
                            <option value="minor">{line.item?.minorUnitName || "وحدة"}</option>
                          )}
                        </select>
                      ) : (
                        <span className="text-xs">{getUnitName(line.item, line.unitLevel)}</span>
                      )
                    ) : (
                      <span className="text-xs text-muted-foreground">—</span>
                    )}
                  </td>

                  {/* الكمية */}
                  <td className="text-center">
                    {isDraft ? (
                      hasExpiry && line.lotId ? (
                        <Input
                          type="number"
                          defaultValue={line.quantity}
                          min={0} step="any"
                          onChange={(e) => pendingQtyRef.current.set(line.tempId, e.target.value)}
                          onBlur={() => handleQtyConfirm(line.tempId)}
                          onKeyDown={(e) => { if (e.key === "Enter") { e.preventDefault(); handleQtyConfirm(line.tempId); } }}
                          className="h-7 text-xs text-center"
                          data-testid={`input-qty-unified-${i}`}
                        />
                      ) : (
                        <Input
                          type="number"
                          value={line.quantity}
                          min={0} step="any"
                          onChange={(e) => updateLine(line.tempId, "quantity", parseFloat(e.target.value) || 0)}
                          className="h-7 text-xs text-center"
                          data-testid={`input-qty-unified-${i}`}
                        />
                      )
                    ) : (
                      <span className="text-xs">{formatNumber(line.quantity)}</span>
                    )}
                  </td>

                  {/* سعر الوحدة */}
                  <td className="text-center">
                    {isDraft ? (
                      <Input
                        type="number"
                        value={line.unitPrice}
                        min={0}
                        onChange={(e) => updateLine(line.tempId, "unitPrice", parseFloat(e.target.value) || 0)}
                        className="h-7 text-xs text-center"
                        data-testid={`input-price-unified-${i}`}
                      />
                    ) : (
                      <span className="text-xs">{formatNumber(line.unitPrice)}</span>
                    )}
                  </td>

                  {/* خصم % */}
                  <td className="text-center">
                    {isDraft ? (
                      <Input
                        type="number"
                        value={line.discountPercent}
                        min={0} max={100}
                        onChange={(e) => updateLine(line.tempId, "discountPercent", parseFloat(e.target.value) || 0)}
                        className="h-7 text-xs text-center"
                        data-testid={`input-disc-pct-unified-${i}`}
                      />
                    ) : (
                      <span className="text-xs">{formatNumber(line.discountPercent)}</span>
                    )}
                  </td>

                  {/* قيمة الخصم */}
                  <td className="text-center">
                    {isDraft ? (
                      <Input
                        type="number"
                        value={line.discountAmount}
                        min={0}
                        onChange={(e) => updateLine(line.tempId, "discountAmount", parseFloat(e.target.value) || 0)}
                        className="h-7 text-xs text-center"
                        data-testid={`input-disc-amt-unified-${i}`}
                      />
                    ) : (
                      <span className="text-xs">{formatNumber(line.discountAmount)}</span>
                    )}
                  </td>

                  {/* الإجمالي */}
                  <td className="text-center font-bold text-xs">{formatNumber(line.totalPrice)}</td>

                  {/* حذف */}
                  {isDraft && (
                    <td className="text-center">
                      <Button
                        variant="ghost" size="icon"
                        onClick={() => removeLine(line.tempId)}
                        data-testid={`button-remove-line-unified-${i}`}
                      >
                        <X className="h-3 w-3 text-destructive" />
                      </Button>
                    </td>
                  )}
                </tr>
              );
            })}
            {lines.length === 0 && (
              <tr>
                <td colSpan={colSpanFull} className="text-center text-muted-foreground py-6 text-sm">
                  لا توجد بنود — أضف خدمة أو صنف باستخدام أزرار الإضافة أعلاه
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* ملخص عدد البنود حسب النوع */}
      {lines.length > 0 && (
        <div className="flex flex-row-reverse flex-wrap gap-2 text-xs text-muted-foreground">
          {(["service", "drug", "consumable", "equipment"] as KnownLineType[])
            .map(t => {
              const count = lines.filter(l => l.lineType === t).length;
              if (!count) return null;
              const cfg = LINE_TYPE_CONFIG[t];
              return (
                <Badge key={t} variant="outline" className={`text-[10px] px-2 ${cfg.className}`}>
                  {cfg.label}: {count}
                </Badge>
              );
            })}
          <span className="mr-auto">إجمالي البنود: {lines.length}</span>
        </div>
      )}
    </div>
  );
}
